blank_issues_enabled: false

issue_templates:
  - name: ğŸ› Bug Report
    path: bug_report.yml
    description: Report something that isn't working as expected.
  - name: ğŸš€ Feature Request
    path: feature_request.yml
    description: Suggest a new feature or enhancement.
  - name: ğŸ”§ Dev Task
    path: dev_task.yml
    description: Internal development TODOs or technical tasks.

contact_links:
  - name: Questions or Help
    url: https://www.pads.rwth-aachen.de/cms/PADS/Der-Lehrstuhl/Team/Wissenschaftliche-Mitarbeiter/~mzkqs/Istvan-Koren/
    about: For direct inquiries, please send an email.
