blank_issues_enabled: false
contact_links:
  - name: â“ Questions or Help
    url: https://www.pads.rwth-aachen.de/cms/PADS/Der-Lehrstuhl/Team/Wissenschaftliche-Mitarbeiter/~mzkqs/Istvan-Koren/
    about: For direct inquiries, please send an email.
